"""
Django settings for mysite project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
import os
import environ

# Build paths inside the projectccls
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
# Read .env file from the project root directory
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(str(env_file))
    print(f"[Security] Loaded environment variables from: {env_file}")
else:
    print(f"[WARNING] .env file not found at: {env_file}")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-@=2jh*jwvj#7=oh+4+ae2)y9j4ixy@f4l^5sf-3iv$2elvp4y#')

# Shared key for server-to-server calls between Django and the Next.js server
# (used by the automatic Monday Weekly Report email to generate its PDF)
WEEKLY_INTERNAL_KEY = env('WEEKLY_INTERNAL_KEY', default='aps-weekly-internal-2026')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)  # Set to True for demo

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# Session Configuration - Use database sessions to avoid Redis conflicts
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
print("Using database sessions to avoid Redis conflicts during sync operations")

SESSION_COOKIE_AGE = 86400  # Keep users logged in for 1 day
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to cookies
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request for long operations
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session active after closing the browser
SESSION_COOKIE_SAMESITE = 'Lax'  # Prevent session issues with CSRF

# CSRF Settings for better security and to prevent CSRF failures
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)  # Set to True if using HTTPS
CSRF_COOKIE_HTTPONLY = env.bool('CSRF_COOKIE_HTTPONLY', default=False)  # Must be False so AJAX can read the token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_AGE = 86400  # 24 hours
CSRF_COOKIE_NAME = 'csrftoken'  # Default CSRF cookie name
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'  # Default CSRF header name
CSRF_TOKEN_COOKIE_NAME = 'csrftoken'  # Ensure consistency
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF tokens
CSRF_COOKIE_PATH = '/'  # Make CSRF cookie available site-wide
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://127.0.0.1:8000',
    'https://localhost:8000',
    'https://portal.fsa-pty.co.za',
    'http://portal.fsa-pty.co.za',
    'https://agricultural-production.fsa-pty.co.za',
    'http://agricultural-production.fsa-pty.co.za',
    'https://aps-demo.fsa-pty.co.za',
    'http://aps-demo.fsa-pty.co.za',
    'https://v4-project.moc-pty.com',
    'http://v4-project.moc-pty.com',
    'https://portal-test.fsa-pty.co.za',
    'http://portal-test.fsa-pty.co.za',
]

CSRF_FAILURE_VIEW = 'main.views.core_views.csrf_failure'

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', 'portal.fsa-pty.co.za', 'portal-test.fsa-pty.co.za', '82.25.97.159', '167.88.43.168', 'v4-project.moc-pty.com'])

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Must be before staticfiles to override runserver
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Compress API responses. The analytics payload is ~3 MB of highly
    # repetitive JSON (13k inspection rows sharing the same eight keys) and
    # gzips about 19x, to ~170 KB. Nothing downstream reads the body, so this
    # is transparent to every view. Must sit above anything that inspects or
    # rewrites the response body.
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Enables static file serving in production
    'main.middleware.ApiAuthJsonMiddleware',  # Convert /api login-redirects to JSON 401 (avoid proxy 502)
    'main.middleware.SecurityHeadersMiddleware',  # Custom security headers middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'main.middleware.ApiLoginRequiredMiddleware',  # All /api/ endpoints require a session (exempt: login, verify-otp)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.SessionTimeoutMiddleware',  # Custom session timeout middleware
    'main.middleware.ActivityLoggingMiddleware',  # Custom activity logging middleware
    'main.middleware.CurrentUserMiddleware',  # Stores current user for audit signals
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database Configuration - Connected to production DB (master branch)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Read from the environment (Docker/production); fall back to the local
        # dev values so nothing changes when running outside a container.
        'NAME': env('DB_NAME', default='v4_inspection'),
        'USER': env('DB_USER', default='inspection_user'),
        'PASSWORD': env('DB_PASSWORD', default='InspectionTest2026'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='5432'),
    },
}

# Use local memory cache for development (no Redis dependency)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Server settings to handle large responses
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB (increased from 50MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB (increased from 50MB)
MAX_UPLOAD_SIZE = 104857600  # 100MB (increased from 50MB)

# Increase timeout for large responses
REQUEST_TIMEOUT = 300  # 5 minutes
RESPONSE_TIMEOUT = 300  # 5 minutes

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Johannesburg'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Static files in development
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Static files collected for production

# Performance and timeout settings to prevent broken pipes
# Note: DATA_UPLOAD_MAX_MEMORY_SIZE is set above to 50MB (line 144)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Allow more form fields
DATA_UPLOAD_MAX_NUMBER_FILES = 100  # Allow more files

# WhiteNoise settings (Compress and Cache static files)
# Using CompressedStaticFilesStorage instead of Manifest version for better compatibility
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Media files (User uploads)
MEDIA_URL = '/media/'

# Local Media Storage
MEDIA_ROOT = str(BASE_DIR / 'media')  # Local media storage


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# =============================
# OneDrive Integration Settings
# =============================
# Azure app registration values - Load from environment variables
ONEDRIVE_CLIENT_ID = env('ONEDRIVE_CLIENT_ID', default='')
ONEDRIVE_CLIENT_SECRET = env('ONEDRIVE_CLIENT_SECRET', default='')
# Use production server URL for OneDrive callback
ONEDRIVE_REDIRECT_URI = env('ONEDRIVE_REDIRECT_URI', default='http://127.0.0.1:8000/onedrive/callback')

# Feature flags
ONEDRIVE_ENABLED = True
PREFER_ONEDRIVE = True

# ZIP File Auto-Organization Settings
AUTO_ORGANIZE_ZIP_FILES = True  # Automatically organize ZIP files by inspection number

# Email Configuration - Using Microsoft Graph API (Same as E-Click project)
EMAIL_BACKEND = 'main.graph_email_backend.GraphEmailBackend'
DEFAULT_FROM_EMAIL = 'foodsafetyagency.aps@afsq.co.za'

# Frontend URL for email links (OTP setup, password reset, etc.)
SITE_URL = env('SITE_URL', default='http://localhost:3000')

# Microsoft Graph API Credentials
GRAPH_CLIENT_ID = env('GRAPH_CLIENT_ID', default='')
GRAPH_CLIENT_SECRET = env('GRAPH_CLIENT_SECRET', default='')
GRAPH_TENANT_ID = env('GRAPH_TENANT_ID', default='')
# Comma-separated list of internal domains whose addresses should never be
# flagged as bounced (e.g. staff sender/CC addresses extracted from NDR bodies)
GRAPH_INTERNAL_DOMAINS = env('GRAPH_INTERNAL_DOMAINS', default='fsa-pty.co.za,moc-pty.com,afsq.co.za')

# Xero Accounting Integration (Web App - created March 5, 2026)
XERO_CLIENT_ID = env('XERO_CLIENT_ID', default='48718D689A564D20AF03CEE9E8D8563E')
XERO_CLIENT_SECRET = env('XERO_CLIENT_SECRET', default='hZ6yz1lwe_TYrcQ_T1z90bDKViSirJgz75M_tki9Synl3T9s')
XERO_REDIRECT_URI = env('XERO_REDIRECT_URI', default='http://localhost:8000/xero/callback/')

# Legacy SMTP Configuration (Backup)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-mail.outlook.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'FoodSafetyAgency@outlook.com')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'FoodSafetyAgency@outlook.com')
EMAIL_TIMEOUT = 30  # Connection timeout in seconds

# =============================
# ENHANCED SECURITY SETTINGS
# =============================

# HTTPS/SSL Security
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)  # Redirect all HTTP to HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if env.bool('USE_X_FORWARDED_PROTO', default=False) else None
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)  # HTTP Strict Transport Security (0 = disabled)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)

# Content Security & Headers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME-sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS protection
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking (already set via middleware)

# Additional Security Settings
SECURE_REFERRER_POLICY = 'same-origin'  # Control referrer information
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # Prevent cross-origin attacks

# File Upload Security
ALLOWED_UPLOAD_EXTENSIONS = [
    '.pdf', '.doc', '.docx', '.xls', '.xlsx',
    '.jpg', '.jpeg', '.png', '.gif', '.bmp',
    '.zip', '.rar', '.7z',
    '.txt', '.csv'
]
MAX_FILE_SIZE_MB = 100  # Maximum file size in megabytes (increased from 50MB)