# Generated by Django 6.0.6 on 2026-09-04 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_emailautomation_per_inspector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedInspectionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(db_index=True, help_text='Primary key the inspection had')),
                ('remote_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('inspection_group_ref', models.PositiveIntegerField(blank=True, db_index=True, help_text='Group the inspection belonged to (plain int: survives the group being deleted too)', null=True)),
                ('client_name', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('commodity', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_inspection', models.DateField(blank=True, db_index=True, null=True)),
                ('inspector_name', models.CharField(blank=True, default='', max_length=100)),
                ('snapshot', models.JSONField(default=dict)),
                ('documents', models.JSONField(default=list)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(blank=True, default='', help_text='Request path the delete came from, e.g. /api/edit-inspection-group/', max_length=200)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_to_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the inspection recreated by the restore', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_deletions', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_restores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Inspection Archive',
                'verbose_name_plural': 'Deleted Inspection Archive',
                'db_table': 'deleted_inspection_archive',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['-deleted_at'], name='idx_dia_date'), models.Index(fields=['deleted_by', '-deleted_at'], name='idx_dia_user_date'), models.Index(fields=['client_name', '-deleted_at'], name='idx_dia_client_date'), models.Index(fields=['original_id'], name='idx_dia_original')],
            },
        ),
    ]
