# Generated by Django 6.0.6 on 2026-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_foodsafetyagencyinspection_lab_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailautomation',
            name='report_type',
            field=models.CharField(choices=[('full', 'Full inspector-management report'), ('manager', 'Manager report (includes financials)'), ('finance', 'Finance report (no revenue figures)')], default='full', help_text='Which weekly report PDF to attach. Ignored when per_inspector is on.', max_length=10),
        ),
    ]
