"""Sends the automatic weekly emails (Email Automation page).

Each EmailAutomation has its own switch, wording, schedule and recipient
list. Two modes:

- Group report: everyone on the list gets the same email with the full
  Weekly Report PDF (the whole inspectorate).
- Individual report (per_inspector=True): every recipient gets a personal
  email with ONLY THEIR OWN numbers and a personal PDF — an inspector sees
  their own inspections, samples, compliance and travel, nobody else's.

PDFs are generated by the Next.js server with the same code as the on-screen
export. Every attempt is logged so a failed or missed send is visible. The
reports contain no financial data.
"""
import datetime
import logging
import os

import requests
from django.conf import settings as dj_settings
from django.core.mail import EmailMultiAlternatives

from ..models import EmailAutomation, WeeklyEmailLog

logger = logging.getLogger(__name__)

# Where the two local servers live (overridable per environment)
DJANGO_BASE = os.environ.get('WEEKLY_DJANGO_URL', 'http://localhost:8001')
FRONTEND_BASE = os.environ.get('WEEKLY_FRONTEND_URL', 'http://localhost:3000')

# Addresses that must NEVER receive these emails, under any circumstances.
BLOCKED_RECIPIENTS = {'louislewies@gmail.com'}


def _key():
    return getattr(dj_settings, 'WEEKLY_INTERNAL_KEY', '')


def previous_week(today=None):
    """The last completed Monday-Sunday week."""
    today = today or datetime.date.today()
    start = today - datetime.timedelta(days=today.weekday() + 7)
    return start, start + datetime.timedelta(days=6)


def is_due_now(automation, now=None):
    """True when this automation's schedule says it should send this hour."""
    now = now or datetime.datetime.now()
    if now.hour != automation.send_hour:
        return False
    if automation.schedule_type == 'daily':
        return True
    if automation.schedule_type == 'monthly':
        return now.day == automation.send_day_of_month
    return now.weekday() == automation.send_day_of_week  # weekly


def _period_start(automation, now=None):
    """Start of the current schedule period — used so retries within the
    same period don't send twice."""
    now = now or datetime.datetime.now()
    today = now.date()
    if automation.schedule_type == 'daily':
        return today
    if automation.schedule_type == 'monthly':
        return today.replace(day=1)
    return today - datetime.timedelta(days=today.weekday())  # this week's Monday


def _fetch_report_data(week_start, week_end):
    url = f"{DJANGO_BASE}/api/weekly-report/?date_from={week_start}&date_to={week_end}"
    r = requests.get(url, headers={'X-Internal-Key': _key()}, timeout=120)
    r.raise_for_status()
    data = r.json()
    if not data.get('success'):
        raise RuntimeError(data.get('error') or 'Report API returned an error')
    return data


def _fetch_pdf(week_start, week_end, inspector=None, report_type=None):
    url = f"{FRONTEND_BASE}/api/weekly-report/pdf?date_from={week_start}&date_to={week_end}"
    if inspector:
        from urllib.parse import quote
        url += f"&inspector={quote(inspector)}"
    elif report_type and report_type != 'full':
        # ?type=manager / ?type=finance — picks which builder the frontend uses.
        url += f"&type={report_type}"
    r = requests.get(url, headers={'X-Internal-Key': _key()}, timeout=180)
    r.raise_for_status()
    if not r.content.startswith(b'%PDF'):
        raise RuntimeError('PDF endpoint did not return a PDF')
    return r.content


def _match_inspector(email):
    """Full name of the system user with this email, or None."""
    from django.contrib.auth import get_user_model
    u = get_user_model().objects.filter(email__iexact=email.strip()).first()
    if not u:
        return None
    return f"{u.first_name} {u.last_name}".strip() or u.username


def _row_for(data, key, inspector_name):
    low = inspector_name.strip().lower()
    for r in data.get(key, []):
        if str(r.get('inspector_name', '')).strip().lower() == low:
            return r
    return None


def _totals_fills(data, week_label):
    t = data.get('totals', {})
    return {
        'week': week_label,
        'name': '',
        'inspections': str(t.get('inspections', 0)),
        'compliance': '-' if t.get('overall_compliance') is None else f"{t['overall_compliance']}%",
        'samples': str(t.get('samples', 0)),
        'km': f"{t.get('total_km', 0):,.1f}".replace(',', ' '),
    }


def _inspector_fills(data, inspector_name, week_label, first_name):
    perf = _row_for(data, 'performance', inspector_name)
    comp = _row_for(data, 'compliance', inspector_name)
    samp = _row_for(data, 'samples', inspector_name)
    trav = _row_for(data, 'travel', inspector_name)
    return {
        'week': week_label,
        'name': first_name,
        'inspections': str(perf['weekly_inspections'] if perf else 0),
        'compliance': f"{comp['rate']}%" if comp else '-',
        'samples': str(samp['taken'] if samp else 0),
        'km': str(trav['km'] if trav else 0),
    }


def _send_one(automation, to_list, fills, pdf_bytes, pdf_name):
    """Compose and send one email (subject/body filled, signature, PDF and
    the optional extra attachment)."""
    def fill(text):
        for k, v in fills.items():
            text = text.replace('{' + k + '}', v)
        return text

    body_text = fill(automation.body)
    if automation.signature.strip():
        body_text += '\n\n' + automation.signature.strip()

    msg = EmailMultiAlternatives(
        subject=fill(automation.subject),
        body=body_text,
        from_email=dj_settings.DEFAULT_FROM_EMAIL,
        to=to_list,
    )
    if automation.signature_image:
        import mimetypes
        from django.utils.html import escape
        automation.signature_image.open('rb')
        img_bytes = automation.signature_image.read()
        automation.signature_image.close()
        img_name = os.path.basename(automation.signature_image.name)
        img_mime = mimetypes.guess_type(img_name)[0] or 'image/png'
        html = (
            '<div style="white-space:pre-wrap;font-family:Arial,Helvetica,sans-serif;'
            f'font-size:14px;color:#111827;">{escape(body_text)}</div>'
            '<img src="cid:sigimg" alt="Signature" style="max-width:420px;margin-top:10px;" />'
        )
        msg.attach_alternative(html, 'text/html')
        msg.graph_inline_images = [('sigimg', img_name, img_bytes, img_mime)]

    msg.attach(pdf_name, pdf_bytes, 'application/pdf')
    if automation.attachment:
        automation.attachment.open('rb')
        content = automation.attachment.read()
        automation.attachment.close()
        msg.attach(os.path.basename(automation.attachment.name), content)
    msg.send(fail_silently=False)


def send_automation_email(automation, triggered_by='schedule', test_to=None, force=False,
                          manual=False, test_inspector=None):
    """Send one automation's email(s). Returns the log row.

    test_to        -- send only to this address, ignore the switch, log TEST.
    test_inspector -- for individual automations: whose personal report the
                      test shows (default: first inspector in the data).
    force          -- send even if this automation already sent this period.
    manual         -- "Send now" from the page: ignores switch and guard.
    """
    week_start, week_end = previous_week()

    def log(status, recipients='', error=''):
        row = WeeklyEmailLog.objects.create(
            automation=automation, automation_name=automation.name,
            week_start=week_start, week_end=week_end, status=status,
            recipients=recipients, error=str(error)[:4000],
            triggered_by=triggered_by,
        )
        logger.info('Email automation "%s": %s (week %s) %s', automation.name, status, week_start, error or '')
        return row

    rows = []
    if test_to:
        if test_to.strip().lower() in BLOCKED_RECIPIENTS:
            return log('FAILED', error='This address is blocked and can never receive these emails.')
    else:
        if not manual:
            if not automation.enabled:
                return log('SKIPPED_OFF')
            if not force and WeeklyEmailLog.objects.filter(
                automation=automation, status='SENT',
                run_at__gte=_period_start(automation),
            ).exists():
                return log('ALREADY_SENT')
        rows = [
            (r.email, r.name) for r in automation.recipients.filter(active=True)
            if r.email.strip().lower() not in BLOCKED_RECIPIENTS
        ]
        if not rows:
            return log('NO_RECIPIENTS')

    recipients_label = test_to or ', '.join(f"{n} <{e}>" if n else e for e, n in rows)
    try:
        data = _fetch_report_data(week_start, week_end)
        week_label = (
            f"Monday {week_start.strftime('%d %b %Y')} — Sunday {week_end.strftime('%d %b %Y')}"
        )

        if automation.per_inspector:
            # ── Individual reports: each person gets ONLY their own numbers ──
            if test_to:
                insp = (test_inspector or _match_inspector(test_to) or '').strip()
                if not insp:
                    perf_rows = data.get('performance', [])
                    insp = perf_rows[0]['inspector_name'] if perf_rows else ''
                if not insp:
                    return log('FAILED', error='No inspector found to build a test report for.')
                pdf = _fetch_pdf(week_start, week_end, inspector=insp)
                fills = _inspector_fills(data, insp, week_label, insp.split()[0])
                _send_one(automation, [test_to], fills, pdf,
                          f"Weekly-Report_{insp.replace(' ', '-')}_{week_start}_to_{week_end}.pdf")
                return log('TEST', recipients=f"{test_to} (showing {insp}'s report)")

            sent, failures = [], []
            for email, name in rows:
                insp = _match_inspector(email) or name
                try:
                    pdf = _fetch_pdf(week_start, week_end, inspector=insp)
                    fills = _inspector_fills(data, insp, week_label, (name or insp).split()[0] if (name or insp) else '')
                    _send_one(automation, [email], fills, pdf,
                              f"Weekly-Report_{insp.replace(' ', '-')}_{week_start}_to_{week_end}.pdf")
                    sent.append(f"{name} <{email}>" if name else email)
                except Exception as ie:  # noqa: BLE001 — keep sending to the rest
                    logger.exception('Individual report to %s failed', email)
                    failures.append(f"{email}: {ie}")
            if not sent:
                return log('FAILED', error='; '.join(failures) or 'Nothing sent')
            return log('SENT', recipients=', '.join(sent),
                       error=('Some failed — ' + '; '.join(failures)) if failures else '')

        # ── Group report: everyone gets the same full-inspectorate email ──
        rtype = getattr(automation, 'report_type', 'full') or 'full'
        pdf = _fetch_pdf(week_start, week_end, report_type=rtype)
        fills = _totals_fills(data, week_label)
        label = {'manager': 'Manager-Report', 'finance': 'Finance-Report'}.get(rtype, 'Weekly-Report')
        _send_one(automation, [test_to] if test_to else [e for e, _ in rows], fills, pdf,
                  f"{label}_{week_start}_to_{week_end}.pdf")
        return log('TEST' if test_to else 'SENT', recipients=recipients_label)
    except Exception as e:  # noqa: BLE001 — any failure must land in the log
        logger.exception('Email automation "%s" failed', automation.name)
        return log('FAILED', recipients=recipients_label, error=e)


def send_due_automations(triggered_by='schedule', force=False):
    """Run the automations whose schedule says they are due this hour
    (or all of them when force=True). Returns the list of log rows."""
    logs = []
    for a in EmailAutomation.objects.order_by('id'):
        if force or is_due_now(a):
            logs.append(send_automation_email(a, triggered_by=triggered_by, force=force))
    return logs
